# Generated by Django 5.1 on 2024-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'post'], name='api_comment_author__2ee335_idx'),
        ),
    ]
