# Generated by Django 4.2.15 on 2024-08-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together={('slug',)},
        ),
    ]
