# Generated by Django 4.1.13 on 2024-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_edited_profile_is_active_profile_is_verified'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'post'], name='api_comment_author__2ee335_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='api_post_slug_002b07_idx'),
        ),
    ]
