# Generated by Django 4.1.13 on 2024-08-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_api_comment_author__2ee335_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='api_post_slug_002b07_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug', 'author'], name='api_post_slug_8f0984_idx'),
        ),
    ]
